### PR TITLE
Add Pro Dimmer 1PM and 2PM

### PR DESCRIPTION
**Pull request by IngmarStein**
Add support for [Pro Dimmer 1PM](https://kb.shelly.cloud/knowledge-base/shelly-pro-dimmer-1pm) and [Pro Dimmer 2PM](https://kb.shelly.cloud/knowledge-base/shelly-pro-dimmer-2pm).

Requires https://github.com/cubi1337/node-shellies-ds9/pull/1

### CODE REVIEW

**Comment by cubi1337** [comment]
Hi - i will check it tomorrow

**Comment by IngmarStein** [comment]
No rush. Thanks for taking a look!

**Comment by IngmarStein** [comment]
Friendly ping.

**Comment by cubi1337** [comment]
;-) ... yes

**Comment by cubi1337** [comment]
Created Version 1.2.0 
Hopefully everything works. The testing department is drinking beer right now.

**Comment by IngmarStein** [comment]
Cheers! 🍻

**Pull request merged**
