### PR TITLE
Add support for Shelly Pro Dual Cover PM

### PR DESCRIPTION
**Pull request by yorickinghels**
Add support for [ Pro Dual Cover PM](https://kb.shelly.cloud/knowledge-base/shelly-pro-dual-cover-pm).

Requires https://github.com/cubi1337/node-shellies-ds9/pull/3

### CODE REVIEW

**Comment by yorickinghels** [comment]
@cubi1337 could you take a look?

**Comment by cubi1337** [comment]
Hi, i will Check within the next days… thx.

**Comment by yorickinghels** [comment]
The one thing I didn't add (should investigate how exactly), is the ability to select the type of cover (window, cover, door).

**Comment by cubi1337** [comment]
thx.

**Comment by cubi1337** [comment]
Got Error:

`src/device-delegates/shelly-pro-dual-cover-pm.ts:2:3 - error TS2305: Module '"shellies-ds9"' has no exported member 'ShellyProDualCoverPm'.

2   ShellyProDualCoverPm,
    ~~~~~~~~~~~~~~~~~~~~

src/device-delegates/shelly-pro-dual-cover-pm.ts:14:45 - error TS2345: Argument of type '{ active: true; type: string; }' is not assignable to parameter of type 'Partial<AddCoverOptions>'.
  Object literal may only specify known properties, and 'type' does not exist in type 'Partial<AddCoverOptions>'.
14     this.addCover(d.cover0, { active: true, type: 'windowCovering' });
                                               ~~~~~~~~~~~~~~~~~~~~~~

src/device-delegates/shelly-pro-dual-cover-pm.ts:15:45 - error TS2345: Argument of type '{ active: true; type: string; }' is not assignable to parameter of type 'Partial<AddCoverOptions>'.
  Object literal may only specify known properties, and 'type' does not exist in type 'Partial<AddCoverOptions>'.

15     this.addCover(d.cover1, { active: true, type: 'windowCovering' });
                                               ~~~~~~~~~~~~~~~~~~~~~~`




We're going on vacation for 3 weeks tomorrow. Unfortunately I don't have time to analyze the error now. If you find the time, you're welcome to take a look. If necessary, I could build the version(s) again today.

**Comment by yorickinghels** [comment]
Are you sure you build the other repo new code correctly before publishing? It seems that the files related to the new device are not in the dist folder of the shellies-ds9 package.

Don't forget if you rebuild and would up the version number, that it also needs to be increased in the dependency of the other repository.

**Comment by cubi1337** [comment]
mhm - I'll check that when I get back from vacation. Sorry

**Comment by Ntb1989** [comment]
Hi @cubi1337 is it possible to add support to this app for the Shelly plus plug uk?

https://www.shelly.com/en-gb/products/product-overview/shelly-plus-plug-uk?srsltid=AfmBOorKwANsWaywYaG520oHzrdWFg5_BmMo5Y7N4FcmdYuuTFdImdjl

**Comment by cubi1337** [comment]
> Are you sure you build the other repo new code correctly before publishing? It seems that the files related to the new device are not in the dist folder of the shellies-ds9 package.
> 
> Don't forget if you rebuild and would up the version number, that it also needs to be increased in the dependency of the other repository.

I checked again - it was true...unfortunately ;)

Now i get following error:

Object literal may only specify known properties, and 'type' does not exist in type 'Partial<AddCoverOptions>'

Your Code: 

export interface AddCoverOptions {
  /**
   * Whether the accessory should be active.
   */
  active: boolean;
  /**
   * Whether the device has a single cover.
   */
  single: boolean;
}


That can't actually work!?

**Comment by cubi1337** [comment]
> Hi @cubi1337 is it possible to add support to this app for the Shelly plus plug uk?
> 
> https://www.shelly.com/en-gb/products/product-overview/shelly-plus-plug-uk?srsltid=AfmBOorKwANsWaywYaG520oHzrdWFg5_BmMo5Y7N4FcmdYuuTFdImdjl

next Version.

**Pull request merged**
